version: "3.9"

services:
  aura_mongo:
    image: mongo:7
    container_name: aura_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: aura_admin
      MONGO_INITDB_ROOT_PASSWORD: aura_pass
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js
    networks:
      - aura_network

  aura_mongo_express:
    image: mongo-express
    container_name: aura_mongo_express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: aura_mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: aura_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: aura_pass
      ME_CONFIG_BASICAUTH: "false"
    ports:
      - "8081:8081"
    depends_on:
      - aura_mongo
    networks:
      - aura_network

networks:
  aura_network:
    external: true
